name: "Bug Report"
description: "Report a bug to help us improve the mod"
title: "[BUG] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 
        Before submitting, please ensure you have checked the **Troubleshooting** section in the README.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have enabled **Debug Mode** and checked the trap status.
          required: true
        - label: I have ensured all prerequisite mods (CBA, ACE, TaroTripwire) are up to date.
          required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe what happened...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Place a [TaroTripWire] in front of a door.
        2. Initialize the trap with the code in README.
        3. Open the door...
    validations:
      required: true

  - type: input
    id: dump_text
    attributes:
      label: DumpText
      description: >
        Paste the dump text here. You can copy the dump data of a specific trap to your clipboard 
        by calling this function with the Trap ID as the first argument: [0] call btd_trap_fnc_dumpToClipboard
      placeholder: '[["doorBuilding",2cd70f40b80# 134781: cwa_budova4_in.p3d Land_cwa_budova4_in],["doorObject","dvere1"],["isSpawn",true],["trapObject",138541: taro_tripwire_1_5m.p3d taro_tripwire_1_5m_Ammo],["id",0],["position",[10469,9668.68,0.00685501]]]'
    validations:
      required: true
        
  - type: textarea
    id: additional
    attributes:
      label: Additional Information / Screenshots
      description: Add any other context or drag-and-drop screenshots here.
    validations:
      required: false