name = "BoobyTrappedDoor"
author = "CatalpaBow"
prefix = "btd"
mainprefix = "z"
git_hash = 0

[hemtt.launch.default]
workshop = [
    "450814997",    # CBA_A3's Workshop ID
    "463939057",    # Ace3
    "583496184",    # CUP Terrains Core
    "853743366",    # CUP Terrains CWA
    "583544987",    # CUP Terrains - Maps
    "3034379807",   # Taro Tripwire

]
parameters = [
    "-skipIntro",           # These parameters are passed to the Arma 3 executable
    "-noSplash",            # They do not need to be added to your list
    "-showScriptErrors",    # You can add additional parameters here
    "-debug",
    "-filePatching",
]
mission = "dev_boobyTrapDoor.cain"